# Generated by Django 2.2.5 on 2019-09-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.CharField(max_length=50),
        ),
    ]
