# Generated by Django 2.2.5 on 2019-09-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190909_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
